language: node_js

node_js:
  - "4"
  - "6"

matrix:
  allow_failures:
    - node_js: "6"

addons:
  apt:
    packages:
      - dh-make
      - devscripts
      - debhelper
      - git

after_success:
 - ./extra/make-testcoveralls.sh

before_deploy:
 - ./extra/make-deb.sh

deploy: 
  provider: bintray
  file: .bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  on:
    branch: master
    node: "0.10"

notifications:
  slack:
    rooms:
    - secure: "BXEmODG5+N5MBYsNygzLE3HOZ6FC/MSgoMB7/1BVakQ8z/jjQMiN/loyOa7x/BcOOLIHG3b8ywlqi3a8zaUn1LUhQBagwU5YXt7ViCQX6TIPU54zkdgaJJMQYj7sXuuGa+Dju4ZxCsf1N1zuJXjJvRsHy1fa+O5jAmiRweBxTmi8I9EtUJocUYQDIbZtbFQQJC2m8WDAT9bloNDM5XolEeCTwV222Bb7aayBbGJxWbRGvPgwkOIhEV9hr90CW2OuBb16FEt+Uhmgpx+rfJPA7vVUCqD76NJUEB4rRYeu2E8w9StUIpu6Vz9zIQKCYWivV2UZsc/APZxgIPz9q+9H4AcorEXNBLSLIyl+XKyEb5SO1O3KTC3OxCQjpdzyT5QhcM5SRIcGMXRuSZZlCCxRsQwbVSE0axhzF9EPlGJQkUWSLG5zG2dEJKp/JHgvvPjSJqatDcYeWNt2xeOAumuuTR4XqdACwrNm0Ljf4J625/RE8GMh44ZBrLduL+lgpNAlB2KT/8j3xlNOJoOq/SmTvAo46KG8vH16LnjmJr/G1Ba8ATQxQWD2aNmPOt71N1m1KPC8sYSF3UTZtmVu/snuzrFpDkQCw4f3O545fxaB8y1IRNgFdGOTEL+iS4Wtzcugn4GKr16o9Xbwkq6yEo6VR6BY/zJNv/WIdouoTwbCMKI="
    on_success: never
    on_failure: always
    on_start: never
